### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by ArjunKaushik1** [theMaxK/Project-Repository#4]
two technical issues/bugs/suggestions
- your website is very nice and the way you have made the pages flow is really good. a suggestion would be to maybe provide direct links to sections that you have links for in your sitemap like under Epoches.
- sometimes it can get confusing as to where the navigation bar is and you have to keep clicking it. maybe you can add a function for clicking on the top left where it says architectural best
two suggestions on content
- on your page about architecture you talk about the history and famous architects. Maybe you can break this up and provide a larger list like you did for styles
- You should also try to make the formatting of all cells in a table to be the same for your pages to make the pages look tidier.

**Comment by theMaxK** [comment]
Thank you for your thorough feedback! 
I turned the architectural best label into a clickable button, broke up the content into two pages and will work something out for the cells.
